### ISSUE TITLE
SE crash on Type="giberrish" of Unlock within aux_research.xml

### ISSUE THREAD

**Issue by Akuukis** [Equinox-/ResearchCore#10]
SpaceEngineers.log
```
2018-05-01 19:24:38.238 - Thread:   1 ->  Exception occured: System.Exception: Failed to parse definition ID asdf/AutomaticRifle
   at Equinox.ResearchCore.Utils.Utilities.Convert(String type, String subtype)
   at Equinox.ResearchCore.Utils.NullableDefinitionId.get_Id()
   at Equinox.ResearchCore.Definition.ResearchDefinition.<>c.<.ctor>b__8_0(NullableDefinitionId x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Equinox.ResearchCore.Definition.ResearchDefinition..ctor(Ob_ResearchDefinition ob)
   at Equinox.ResearchCore.Definition.ResearchDefinitionManager.DefinitionBuilder.Build()
   at Equinox.ResearchCore.Definition.ResearchDefinitionManager.FinishLoading()
   at Equinox.ResearchCore.ResearchManager.LoadResearchData()
   at Equinox.ResearchCore.ResearchManager.Attach()
   at Equinox.ResearchCore.ResearchCore.DoInit()
   at Equinox.ResearchCore.ResearchCore.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

But if subtype is wrong, then it logs warning and doesn't crash.

**Comment by Equinox-** [comment]
Since having a wrong type is a symptom of bad configuration, and a wrong subtype is a symptom of not having the mod this is working as intended.
